### ISSUE TITLE
Add individual subjects

### ISSUE THREAD

**Issue by mazarafa** [f2acode/computeiro#7]
It's a brilliant idea, brother.

Can we put something from graph theory and research (about AI, and constantly evolving technologies), how about?

**Comment by f2acode** [comment]
I'm glad you enjoyed it!
To be able to add new contents about computer science in general (instead of just POSCOMP exams) we have two tasks:

1. Change the app structure to create a new section for this type of content;
2. Chose the source from where we're gonna request the contents.

If you have time to help me with that, feel free! :smile:

**Comment by f2acode** [comment]
Hey @mazarafa! I just changed the section of POSCOMP exams, so now it's possible to add many different contents and categories (check my recent commits), feel free to contribute with content you think it's good :smile: (there is a json on the project, i will update readme later)
